# Loacl Profile
spring:
    profiles: local
    
    #application:
     #    name: consumerdemo_local

server:
    port: 8752   
                
pcf:
  application: consumerdemo_local
  space: "development"
  memory: "512M"
  diskQuota: "512M"
  instances: 1
  organization: springboot-org
  target:  https://api.run.pivotal.io
  
log:
    level: info

---
# Dev Profile
spring:
    profiles: dev
   
    #application:
     #    name: consumerdemo_dev

server:
    port: 8752
                
pcf:
  application: consumerdemo_dev
  space: "development"
  memory: "512M"
  diskQuota: "512M"
  instances: 1
  organization: springboot-org
  target:  https://api.run.pivotal.io
  
log:
    level: info

---
# VST0 Profile
spring:
    profiles: vst0
    
    #application:
     #    name: consumerdemo_vst0
server:
    port: 8753
    
pcf:
  application: consumerdemo_vst0
  space: "development"
  memory: "512M"
  diskQuota: "512M"
  instances: 1
  organization: springboot-org
  target:  https://api.run.pivotal.io

log:
    level: info