# Dev Profile
spring:
    profiles: dev

welcome:
    message: Welcome to your first Spring Boot app with DEV env!

#datasource:
 # url: jdbc:postgres://aolsqtkg:Cj1QhBT7fgX98m-7ni0IXgQEBiewrD--@pellefant-02.db.elephantsql.com:5432/aolsqtkg
   # driver-class-name: org.postgresql.Driver
    #username: b6e69ac3acfbb4
    #password: 22469be6
 #   url: ${vcap.services.elephantsql.credentials.uri}
    #username: ${vcap.services.elephantsql.credentials.username}
    #password: ${vcap.services.elephantsql.credentials.password}
          
pcf:
  application: SpringBootRestService_dev
  space: "development"
  memory: "512M"
  diskQuota: "512M"
  instances: 1
  organization: RakeshKumar-Org
  target:  https://api.run.pivotal.io

log:
    level: info

---
# VST0 Profile
spring:
    profiles: vst0

welcome:
    message: Welcome to your first Spring Boot app with VST0 env!

pcf:
  application: SpringBootRestService_dev
  space: "development"
  memory: "1024M"
  diskQuota: "1024M"
  instances: 1
  organization: RakeshKumar-Org
  target:  https://api.run.pivotal.io

log:
    level: info